### ISSUE TITLE
ClusterIP for PGHOST (postgres host) should be passed to the postgrest pod explicitly instead of using environment variable added by kubelet

### ISSUE THREAD

**Issue by Jordan396** [kubeinn/kubeinn#7]
```
command:
        - echo "db-uri       = \"postgres://$(PGUSER):$(PGPASSWORD)@$(KUBEINN_POSTGRES_CLUSTER_IP_SERVICE_V_1_0_0_A_1_SERVICE_HOST):$(PGPORT)/$(PGDATABASE)\"" >> /etc/postgrest.conf
        env:
          - name: PGHOST
            value: $(POSTGRES_CLUSTER_IP_SERVICE)
```
Note that if the name of the ClusterIP service (KUBEINN_POSTGRES_CLUSTER_IP_SERVICE_V_1_0_0_A_1_SERVICE_HOST) changes, the application will break. ClusterIP for PGHOST (postgres host) should be passed to the postgrest pod explicitly. One possible solution would be to perform an nslookup for kubeinn-postgres-cluster-ip-service-v-1-0-0-a-1.
